#
# Default configuration settings. Settings can be changed here or by overriding
# the values in local.yml defined in the same directory.
#

# MQTT settings
mqtt:
  url: mqtt://test.mosquitto.org:1883

  # MQTT.js client options (https://github.com/mqttjs/MQTT.js#client)
  clientOptions:
    username:
    password:
    will:
      topic: analog-ctrl/status
      payload: offline
      qos: 1
      retain: true

  # MQTT topics to publish analog input values
  topic:  analog-ctrl

  # MQTT online status settings
  status:
    topic: analog-ctrl/status
    payload: online
    options:
      qos: 1
      retain: true

# Analog input settings
adc:
  bitRate: 12             # resolution
  readInterval: 500       # milliseconds
  publishTolerance: 1     # value change before publishing
  scaleMinMax: [0, 4096]  # published value min/max boundaries
  analogInputs: [1, 2, 3, 4, 5, 6, 7, 8]
  voltageMinMax:
    1: [0.015, 5.05]
    2: [0.015, 5.05]
    3: [0.015, 5.05]
    4: [0.015, 5.05]
    5: [0.015, 5.05]
    6: [0.015, 5.05]
    7: [0.015, 5.05]
    8: [0.015, 5.05]

logging:
  enabled: true  # log voltages to console
  reset: true    # reset console between readings
